name: "build"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: "install dfx"
      run: |
       wget --no-check-certificate https://sdk.dfinity.org/install.sh
       yes Y | DFX_VERSION=0.5.9 sh install.sh
       echo "::add-path::/home/runner/bin"
    - name: "dfx cache install"
      run: dfx cache install
    - name: "install vessel"
      run: wget --output-document /home/runner/bin/vessel https://github.com/kritzcreek/vessel/releases/download/v0.4.1/vessel-linux64 && chmod +x /home/runner/bin/vessel
    - name: "test"
      run: ./test.sh